name: Docker Test

on:
  push:
    branches:
      - master
jobs:
  build-and-run-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        browsers: [ $(cat browsers.txt) ]

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Build and run tests
      uses: docker/build-push-action@v3
      with:
        context: .
        load: true
        push: false
        tags: robot-framework:latest
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache

    - name: Set permissions for mediamarkt_test directory
      run: sudo chmod 777 .

    - name: Create results directory
      run: mkdir -p results && sudo chmod 777 results

    - name: Run tests in Docker container
      run: docker run --name robot-container -v $(pwd)/results:/usr/src/app/results -e BROWSER=${{ matrix.browsers }} robot-framework:latest

    - name: Copy results
      run: docker cp robot-container:/app/results .

    - name: Remove container
      run: docker stop robot-container && docker rm robot-container

    - name: Upload test results
      uses: actions/upload-artifact@v3
      with:
        name: test-results-${{ matrix.browsers }}
        path: ./results